### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ldecicco-USGS** [usgs/usgs.github.io#1]
If you want to do a similar page as
http://usgs-r.github.io/

The repo is:
https://github.com/USGS-R/usgs-r.github.com

**Comment by ldecicco-USGS** [comment]
On the other hand, if you are trying to do something like this:
http://developer.epa.gov/

That would be so totally awesome.

**Comment by emartinez-usgs** [comment]
GitHub supports "oragnization", "user" and "project" pages. These are accomplished by creating carefully-named repositories (for organization and user pages) or using the gh-pages branch (for project pages).

The problem is that if a custom CNAME is registered for an organization, it hijacks all project pages as well. This is undesirable and the CNAME has been removed.

**Comment by ldecicco-USGS** [comment]
:+1: 
Just passing on how we did ours, in case you wanted a template....and noting that the EPA has a pretty cool page as a completely unrelated comment.
